/*
# Seed Sample Opportunities

This migration adds sample opportunities across all types for demonstration purposes.

## Data Added:
- 10 Internships from various companies
- 5 Hackathons
- 5 Coding Competitions
- 5 Scholarships
- 5 Fellowships
*/

-- Internships
INSERT INTO opportunities (type, title, company, company_logo_url, description, location, work_mode, salary, duration, skills_required, application_url, deadline, tags, is_featured, is_active, source) VALUES
('internship', 'Software Engineering Intern', 'Google', 'https://logo.clearbit.com/google.com', 'Join Google as a Software Engineering Intern and work on products used by billions. You will have the opportunity to work on challenging projects and learn from world-class engineers.', 'Mountain View, CA', 'onsite', '$8,500/month', '12 weeks', ARRAY['Python', 'Java', 'C++', 'Algorithms'], 'https://careers.google.com/jobs/google-intern', '2024-02-28', ARRAY['Big Tech', 'Summer 2024', 'Full-time'], true, true, 'LinkedIn'),
('internship', 'Frontend Developer Intern', 'Meta', 'https://logo.clearbit.com/meta.com', 'Build products that connect billions of people. As a Frontend Developer Intern, you will work on React components and improve user experiences across Meta platforms.', 'Menlo Park, CA', 'hybrid', '$9,000/month', '12 weeks', ARRAY['React', 'JavaScript', 'TypeScript', 'CSS'], 'https://metacareers.com/jobs/meta-intern', '2024-03-01', ARRAY['Big Tech', 'React', 'UI/UX'], true, true, 'LinkedIn'),
('internship', 'Backend Engineering Intern', 'Stripe', 'https://logo.clearbit.com/stripe.com', 'Help build the economic infrastructure for the internet. Work on payment processing APIs and distributed systems at one of the most valuable fintech companies.', 'Remote', 'remote', '$7,500/month', '10 weeks', ARRAY['Ruby', 'Go', 'PostgreSQL', 'Distributed Systems'], 'https://stripe.com/jobs/intern', '2024-02-20', ARRAY['Fintech', 'Backend', 'API'], true, true, 'Indeed'),
('internship', 'Data Science Intern', 'Netflix', 'https://logo.clearbit.com/netflix.com', 'Analyze viewer behavior and improve recommendation algorithms. Work with petabytes of data to enhance the Netflix experience for millions.', 'Los Gatos, CA', 'hybrid', '$8,000/month', '12 weeks', ARRAY['Python', 'SQL', 'Machine Learning', 'Tableau'], 'https://jobs.netflix.com/intern', '2024-02-25', ARRAY['ML', 'Analytics', 'Big Data'], false, true, 'Netflix Careers'),
('internship', 'Cloud Engineering Intern', 'Amazon AWS', 'https://logo.clearbit.com/aws.amazon.com', 'Work on the world leading cloud platform. Build and improve services that millions of businesses rely on daily.', 'Seattle, WA', 'onsite', '$7,800/month', '12 weeks', ARRAY['AWS', 'Python', 'Linux', 'DevOps'], 'https://amazon.jobs/intern', '2024-03-05', ARRAY['Cloud', 'DevOps', 'AWS'], true, true, 'LinkedIn'),
('internship', 'Mobile Developer Intern', 'Spotify', 'https://logo.clearbit.com/spotify.com', 'Build the next generation of music streaming apps. Work on iOS or Android development for hundreds of millions of users.', 'New York, NY', 'hybrid', '$7,000/month', '10 weeks', ARRAY['Swift', 'Kotlin', 'iOS', 'Android'], 'https://lifeatspotify.com/intern', '2024-02-22', ARRAY['Mobile', 'Music', 'Streaming'], false, true, 'Spotify Careers'),
('internship', 'Full Stack Developer Intern', 'Airbnb', 'https://logo.clearbit.com/airbnb.com', 'Help create the future of travel. Work on both frontend and backend systems that power the sharing economy.', 'San Francisco, CA', 'hybrid', '$7,200/month', '12 weeks', ARRAY['React', 'Ruby on Rails', 'PostgreSQL', 'GraphQL'], 'https://careers.airbnb.com/intern', '2024-02-28', ARRAY['Full Stack', 'Travel', 'Marketplace'], false, true, 'Indeed'),
('internship', 'Security Engineering Intern', 'Cloudflare', 'https://logo.clearbit.com/cloudflare.com', 'Protect millions of websites from cyber threats. Work on cutting edge security solutions and distributed systems.', 'Austin, TX', 'Remote', '$6,800/month', '10 weeks', ARRAY['Security', 'Networking', 'Go', 'Rust'], 'https://cloudflare.com/careers/intern', '2024-03-01', ARRAY['Security', 'Networking', 'Infrastructure'], false, true, 'Cloudflare Careers'),
('internship', 'Machine Learning Intern', 'OpenAI', 'https://logo.clearbit.com/openai.com', 'Work on groundbreaking AI research. Contribute to projects that push the boundaries of artificial intelligence.', 'San Francisco, CA', 'onsite', '$10,000/month', '12 weeks', ARRAY['Python', 'PyTorch', 'Transformers', 'Deep Learning'], 'https://openai.com/careers/intern', '2024-02-15', ARRAY['AI/ML', 'Research', 'Deep Learning'], true, true, 'OpenAI Careers'),
('internship', 'DevOps Engineering Intern', 'GitLab', 'https://logo.clearbit.com/gitlab.com', 'Build and improve the CI/CD platform used by millions of developers. Work fully remote with a distributed team.', 'Remote', 'remote', '$6,500/month', '10 weeks', ARRAY['Kubernetes', 'Docker', 'Terraform', 'CI/CD'], 'https://about.gitlab.com/jobs/intern', '2024-03-10', ARRAY['DevOps', 'Remote', 'CI/CD'], false, true, 'GitLab Careers');

-- Hackathons
INSERT INTO opportunities (type, title, company, description, location, work_mode, deadline, start_date, end_date, prize_pool, team_size, skills_required, application_url, tags, is_featured, is_active, source, difficulty) VALUES
('hackathon', 'MIT HackMIT', 'MIT', 'One of the largest student-run hackathons in the world. Build innovative solutions across 48+ hours alongside top student hackers.', 'Cambridge, MA', 'onsite', '2024-09-15', '2024-09-20', '2024-09-22', '$50,000 in prizes', '1-4 members', ARRAY['Innovation', 'Prototyping', 'Design'], 'https://hackmit.org/', ARRAY['University', '48hr', 'High Tech'], true, true, 'Devpost', 'Intermediate'),
('hackathon', 'TreeHacks', 'Stanford', 'Stanford''s flagship hackathon focused on social good. Build projects that make a positive impact on the world.', 'Stanford, CA', 'onsite', '2024-02-17', '2024-02-23', '2024-02-25', '$20,000 in prizes', '2-4 members', ARRAY['Social Impact', 'Web Dev', 'Mobile'], 'https://www.treehacks.com/', ARRAY['Social Good', 'Stanford', '36hr'], true, true, 'Devpost', 'Beginner'),
('hackathon', 'HackUPC', 'Hackers at UPC', 'Barcelona''s premier hackathon. Join 500+ hackers for 36 hours of building, learning, and fun.', 'Barcelona, Spain', 'onsite', '2024-03-01', '2024-03-08', '2024-03-10', '15,000 EUR', '1-4 members', ARRAY['Web Dev', 'Mobile', 'Design'], 'https://hackupc.com/', ARRAY['International', 'Europe', '36hr'], false, true, 'Devpost', 'Intermediate'),
('hackathon', 'ETHGlobal', 'ETHGlobal', 'The world''s largest Ethereum hackathon series. Build the future of web3 and blockchain applications.', 'Remote', 'remote', '2024-04-01', '2024-04-05', '2024-04-07', '$500,000 in prizes', '1-5 members', ARRAY['Solidity', 'Web3', 'Blockchain', 'DeFi'], 'https://ethglobal.com/', ARRAY['Blockchain', 'Web3', 'Crypto'], true, true, 'Devpost', 'Advanced'),
('hackathon', 'Hack the North', 'University of Waterloo', 'Canada''s largest hackathon. 36 hours of learning, building, and connecting with top sponsors.', 'Waterloo, ON', 'onsite', '2024-09-01', '2024-09-13', '2024-09-15', '$100,000 in prizes', '1-4 members', ARRAY['Full Stack', 'AI', 'Hardware'], 'https://hackthenorth.com/', ARRAY['Canada', 'Major Event', '36hr'], false, true, 'Devpost', 'Intermediate');

-- Competitions
INSERT INTO opportunities (type, title, company, description, location, work_mode, deadline, start_date, skills_required, prize_pool, difficulty, application_url, tags, is_featured, is_active, source) VALUES
('competition', 'Google Code Jam', 'Google', 'Google''s flagship coding competition. Solve algorithmic problems and advance through rounds to the world finals.', 'Online', 'remote', '2024-04-01', '2024-03-15', ARRAY['Algorithms', 'Data Structures', 'Competitive Programming'], '$15,000', 'Advanced', 'https://codingcompetitions.withgoogle.com/', ARRAY['Algorithm', 'Global', 'Google'], true, true, 'Codeforces'),
('competition', 'Meta Hacker Cup', 'Meta', 'Meta''s annual programming contest. Test your coding skills against thousands of programmers worldwide.', 'Online', 'remote', '2024-10-01', '2024-09-15', ARRAY['Algorithms', 'Optimization', 'Problem Solving'], '$20,000', 'Advanced', 'https://www.facebook.com/codingcompetitions/', ARRAY['Algorithm', 'Meta', 'Global'], true, true, 'Codeforces'),
('competition', 'LeetCode Weekly Contest', 'LeetCode', 'Weekly programming contests on LeetCode. Great for practice and improving your coding interview skills.', 'Online', 'remote', '2024-01-29', '2024-01-28', ARRAY['Algorithms', 'Data Structures', 'Problem Solving'], 'Contest Points', 'Intermediate', 'https://leetcode.com/contest/', ARRAY['Weekly', 'Interview Prep', 'Practice'], false, true, 'LeetCode'),
('competition', 'Codeforces Round', 'Codeforces', 'Regular competitive programming contests on Codeforces. Open to all skill levels.', 'Online', 'remote', '2024-02-01', '2024-02-01', ARRAY['Competitive Programming', 'Algorithms'], 'Rating Points', 'All Levels', 'https://codeforces.com/contests', ARRAY['Regular', 'All Levels', 'Algorithm'], false, true, 'Codeforces'),
('competition', 'ICPC Regional Contest', 'ICPC', 'The International Collegiate Programming Contest regional round. Team competition for university students.', 'Boston, MA', 'onsite', '2024-10-15', '2024-11-01', ARRAY['Team', 'Algorithms', 'Problem Solving'], 'World Finals Spot', 'Advanced', 'https://icpc.global/', ARRAY['University', 'Team', 'Competitive Programming'], true, true, 'ICPC');

-- Scholarships
INSERT INTO opportunities (type, title, company, description, location, eligibility, deadline, salary, application_url, tags, is_featured, is_active, source) VALUES
('scholarship', 'Google Tech Scholarship', 'Google', 'Full scholarship for women in tech pursuing computer science degrees. Includes mentorship and networking opportunities.', 'United States', 'Women pursuing CS degrees with minimum 3.0 GPA', '2024-03-15', 'Full Tuition + $10,000/year', 'https://buildyourfuture.withgoogle.com/scholarships', ARRAY['Tech', 'Women', 'Underrepresented'], true, true, 'Google'),
('scholarship', 'Microsoft Scholarship', 'Microsoft', 'Academic-year scholarships for students pursuing degrees in computer science and related STEM disciplines.', 'United States', 'STEM majors with demonstrated financial need', '2024-02-28', '$5,000', 'https://microsoft.com/scholarships', ARRAY['STEM', 'Financial Need', 'Microsoft'], false, true, 'Microsoft'),
('scholarship', 'GHC Scholarship', 'AnitaB.org', 'Full scholarship to attend the Grace Hopper Celebration, the largest gathering of women technologists.', 'Orlando, FL', 'Women in computing and engineering fields', '2024-06-15', 'Conference + Travel', 'https://ghc.anitab.org/scholarships', ARRAY['Women', 'Conference', 'Networking'], true, true, 'AnitaB'),
('scholarship', 'Generation Google Scholarship', 'Google', 'Scholarship for underrepresented groups in computer science. Includes leadership development and mentorship.', 'United States', 'Underrepresented minorities in tech', '2024-03-20', '$10,000', 'https://buildyourfuture.withgoogle.com/scholarships/generation-google', ARRAY['Diversity', 'Minorities', 'Leadership'], false, true, 'Google'),
('scholarship', 'SWE Scholarship', 'Society of Women Engineers', 'Scholarships for women pursuing ABET-accredited engineering and computing degrees.', 'United States', 'Female engineering students', '2024-02-15', 'Varies', 'https://swe.org/scholarships', ARRAY['Women', 'Engineering', 'STEM'], false, true, 'SWE');

-- Fellowships
INSERT INTO opportunities (type, title, company, description, location, work_mode, deadline, start_date, duration, salary, skills_required, application_url, tags, is_featured, is_active, source) VALUES
('fellowship', 'MLH Fellowship', 'Major League Hacking', '12-week program where students contribute to open source projects with mentorship from MLH and industry sponsors.', 'Remote', 'remote', '2024-02-28', '2024-06-01', '12 weeks', '$5,000/month', ARRAY['Open Source', 'Git', 'Communication', 'JavaScript'], 'https://fellowship.mlh.io/', ARRAY['Open Source', 'Remote', 'Mentorship'], true, true, 'MLH'),
('fellowship', 'Klarna Fellowship', 'Klarna', '12-month program for aspiring engineers. Work on real products at a leading fintech company.', 'Stockholm, Sweden', 'onsite', '2024-03-15', '2024-09-01', '12 months', 'Market Rate Salary', ARRAY['Full Stack', 'FinTech', 'Payment Systems'], 'https://klarna.com/careers/fellowship', ARRAY['Fintech', 'Full-time', 'International'], false, true, 'Klarna'),
('fellowship', 'Civic Digital Fellowship', 'Civic Digital', 'Build technology for social impact. Work with government agencies to improve public services.', 'Washington, DC', 'hybrid', '2024-02-01', '2024-06-01', '10 weeks', '$7,000/month', ARRAY['Full Stack', 'Civic Tech', 'Data Analysis'], 'https://civicdigital.com/fellowship', ARRAY['Social Impact', 'Government', 'Civic Tech'], true, true, 'Civic Digital'),
('fellowship', 'Recurse Center Retreat', 'Recurse Center', 'Self-directed educational retreat for programmers. Free, self-paced, 12-week program in NYC.', 'New York, NY', 'onsite', '2024-04-01', '2024-06-15', '12 weeks', 'Free Program + Living Stipend', ARRAY['Programming', 'Self-directed', 'Community'], 'https://recurse.com/', ARRAY['Self-directed', 'Non-traditional', 'Community'], false, true, 'Recurse'),
('fellowship', 'Formation Fellowship', 'Formation', '12-week program for early career engineers. Technical training plus career coaching and job placement.', 'Remote', 'remote', '2024-02-15', '2024-05-01', '12 weeks', '$6,000/month', ARRAY['Full Stack', 'Interview Prep', 'Career Development'], 'https://formation.dev/fellowship', ARRAY['Career Dev', 'Remote', 'Mentorship'], false, true, 'Formation');